import * as turf from '@turf/turf';
import { REGIONS } from '../data/regions/index.js';
import { provinces } from './regions.js';

// Region lookups, derived from the generated tree in src/data/regions/.
//
// These used to be a hand-written map of five cities that duplicated the bbox
// and centre already recorded in each boundary file, which meant two places to
// update and a test to police the drift. The tree is generated by
// scripts/build-region-boundaries.mjs from those same boundaries, so there is
// one source now.
//
// bbox is a pre-2025-merger extent. Vietnam merged its provinces in mid-2025, so
// today's official Ho Chi Minh City covers 36,566 km2 and reaches Vung Tau; the
// legacy outline is the area people actually mean by the city.
//
// centre stays the recognisable city centre rather than the polygon's centroid,
// which for an irregular outline can land somewhere no one associates with the
// place. The build honours a per-node override for exactly that reason. The map
// fits the bbox anyway.
//
// Keyed by EVERY node, not just the playable provinces, so a bookmarked
// /game?location=DL still resolves after Da Lat became a district of Lam Dong.
export const CITIES = REGIONS;

export const cityCenters = Object.fromEntries(
  Object.values(REGIONS)
    .filter((region) => region.center)
    .map((region) => [region.code, region.center])
);

export const cityNames = Object.fromEntries(
  Object.values(REGIONS).map((region) => [region.code, region.name])
);

export const cityBboxes = Object.fromEntries(
  Object.values(REGIONS)
    .filter((region) => region.bbox)
    .map((region) => [region.code, region.bbox])
);

// Province list for UI components. Districts are reached by expanding a
// province, not from this flat list.
export const cities = provinces().map((code) => ({
  code,
  name: REGIONS[code].name.toUpperCase()
}));

// Calculate distance between two coordinates in meters using Turf
export function calculateDistance(lat1, lon1, lat2, lon2) {
  if (lat1 === lat2 && lon1 === lon2) return 0;

  try {
    const from = turf.point([lon1, lat1]);
    const to = turf.point([lon2, lat2]);
    const distanceKm = turf.distance(from, to, { units: 'kilometers' });

    // Convert to meters and round
    return Math.round(distanceKm * 1000);
  } catch (error) {
    console.error('Error calculating distance with Turf:', error);
    throw new Error(`Failed to calculate distance: ${error.message}`);
  }
}

// Calculate score based on distance (0-5 points scale)
export function calculateScore(distance) {
  if (distance <= 50) return 5;
  if (distance <= 100) return 4;
  if (distance <= 200) return 3;
  if (distance <= 500) return 2;
  if (distance <= 1000) return 1;
  return 0;
}

// Format distance for display
export function formatDistance(distance) {
  if (distance < 1000) {
    return `${distance}m`;
  } else {
    return `${(distance / 1000).toFixed(2)}km`;
  }
}


// Get or set username from localStorage
export function getUsername() {
  if (typeof window === 'undefined') return null;
  return localStorage.getItem('vngeoguessr_username');
}

export function setUsername(username) {
  if (typeof window === 'undefined') return;
  localStorage.setItem('vngeoguessr_username', username);
}

// Get result message based on score
export function getResultMessage(score, distance) {
  if (score > 4) return "Excellent! Outstanding guess!";
  if (score > 2) return "Good job! Nice work!";
  if (score > 0) return "Not bad! Keep trying!";
  return "Nice try! Better luck next time!";
}

// Get distance color for leaderboard display
export function getDistanceColor(distance) {
  if (distance <= 50) return 'text-green-700 dark:text-green-300';
  if (distance <= 100) return 'text-blue-700 dark:text-blue-300';
  if (distance <= 200) return 'text-yellow-700 dark:text-yellow-300';
  if (distance <= 500) return 'text-orange-700 dark:text-orange-300';
  return 'text-red-700 dark:text-red-300';
}
