// Access to the prebuilt panorama indexes.
//
// Each city ships a list of known panorama ids and their coordinates, built
// offline by scripts/build-pano-index.mjs from Mapillary's vector tiles. Picking
// from a list we already hold replaces asking the Graph API what is near a
// random point, which fails outright in dense districts and takes seconds where
// it works.
//
// Server-side only: these files are large, and nothing in the browser needs them.

// The barrel is generated by scripts/build-pano-index.mjs and lists only the
// cities whose index exists, so a partial build still compiles.
import { PANO_INDEXES } from '../data/panos/index.js';

/**
 * The whole index for a city.
 * @param {string} cityCode City code, e.g. 'TPHCM'.
 * @returns {Object} The index, including its panos array.
 */
export function getCityIndex(cityCode) {
  const index = PANO_INDEXES[cityCode];
  if (!index) {
    throw new Error(
      `No panorama index for city: ${cityCode}. ` +
        'Run: node scripts/build-pano-index.mjs ' + cityCode
    );
  }
  if (!index.panos?.length) throw new Error(`Panorama index for ${cityCode} is empty`);
  return index;
}

/**
 * Pick a random panorama for a city.
 * @param {string} cityCode City code.
 * @param {Set<string>} excludeIds Ids to avoid, e.g. ones already tried.
 * @returns {{id: string, lat: number, lng: number}} The chosen panorama.
 */
export function pickRandomPano(cityCode, excludeIds = new Set()) {
  const { panos } = getCityIndex(cityCode);
  const usable = excludeIds.size > 0 ? panos.filter((p) => !excludeIds.has(p.id)) : panos;
  if (usable.length === 0) throw new Error(`No panoramas left to try for ${cityCode}`);
  return usable[Math.floor(Math.random() * usable.length)];
}

/**
 * How many panoramas a city holds. Useful for diagnostics.
 * @param {string} cityCode City code.
 * @returns {number} Count.
 */
export function countPanos(cityCode) {
  return getCityIndex(cityCode).panos.length;
}

/**
 * City codes that currently have an index built.
 * @returns {string[]} Codes.
 */
export function indexedCities() {
  return Object.keys(PANO_INDEXES);
}
