import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { boundaryEntries, panoEntries, renderBarrel } from '../scripts/lib/barrel.mjs';

// Rebuilds each generated barrel from the files actually on disk through the
// shared emitter in scripts/lib/barrel.mjs, and checks it against the
// committed output byte-for-byte. This is the proof that extracting one
// emitter out of scripts/build-region-boundaries.mjs and
// scripts/build-pano-index.mjs did not change what either script writes.

const BOUNDARY_HEADER =
  '// Generated by scripts/build-region-boundaries.mjs. Do not edit by hand.\n' +
  '//\n' +
  '// Lists only the boundaries that have actually been built, so a partial\n' +
  '// build still compiles.\n\n';

const PANO_HEADER =
  '// Generated by scripts/build-pano-index.mjs. Do not edit by hand.\n' +
  '//\n' +
  '// Lists only the province indexes that have actually been built, so a\n' +
  '// partial build still compiles.\n\n';

// Both scripts write with '\n' only, and that is what git stores. A Windows
// checkout with core.autocrlf=true rewrites that to '\r\n' on disk, which is a
// checkout-time detail, not a content difference the scripts produced -- so
// the committed side is normalised back to '\n' before the comparison.
const committed = (path) => readFileSync(path, 'utf8').replace(/\r\n/g, '\n');

describe('generated barrels', () => {
  it('rebuilds src/data/boundaries/index.js byte-for-byte', () => {
    const dir = resolve('src/data/boundaries');
    const rebuilt = renderBarrel(BOUNDARY_HEADER, 'REGION_BOUNDARIES', boundaryEntries(dir));
    expect(rebuilt).toBe(committed(`${dir}/index.js`));
  });

  it('rebuilds src/data/panos/index.js byte-for-byte', () => {
    const dir = resolve('src/data/panos');
    const rebuilt = renderBarrel(PANO_HEADER, 'PANO_INDEXES', panoEntries(dir));
    expect(rebuilt).toBe(committed(`${dir}/index.js`));
  });
});
